"""Module with project consts"""

REGEXP_PATTERN = r"([^/]+)(?=\.[^.]+$)"
CSV_PATH = "./DataSet/*.csv"
CLEAR_DATA_PARQUET_NAME = "temp_in_cities"
AGG_DATA_BY_CITY = "avg_temp_in_city"
AGG_DATA_PER_DAY = "agg_temp_per_day"
WARM_CITIES_DATA = "warm_cities"
TEMP_ANOMALY_DATA = "anomaly_temp_per_day_in_cities"
DATE_PATTERN = "yyyy-MM-dd HH:mm:ssXXX"
